spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: system
#        - uri: http://127.0.0.1:9001
#        - predicates:
#            - name: Path
#            - args: /system/**
server:
  port: 9000
eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
